### ISSUE TITLE
Update NLTK

### ISSUE THREAD

**Issue by melissacbrown** [umd-mith/geniusing#1]
I was working with the jupyter notebook at master/named-entity-recognition-in-lyrics.ipynb

I noticed. that there is an error in line 2 because StanfordNERTagger is deprecated within NLTK according to this StackOverFlow post that states a rewrite would require using nltk.parse instead of nltk.tag.

https://stackoverflow.com/questions/13883277/stanford-parser-and-nltk/51981566#51981566

**Comment by edsu** [comment]
@melissacbrown thanks for the report! I think this should be doable, assuming the interfaces haven't drastically changed. I'll add this to my todo list and let you know what I find.

**Comment by edsu** [comment]
Hi @melissacbrown I just reran the notebook with StanfordNER v3.9.2 and NLTK v3.4.4 and it seemed to work fine. I made a small change to the notebook to use local paths. Please reopen this ticket, and paste a stack trace from the notebook if you continue to run into problems.
